// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package com.satoshilabs.trezor.lib.protobuf;

public final class TrezorStorage {
  private TrezorStorage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Storage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * version of storage
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     * version of storage
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    boolean hasNode();
    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getNode();
    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder();

    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    boolean hasMnemonic();
    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    java.lang.String getMnemonic();
    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    com.google.protobuf.ByteString
        getMnemonicBytes();

    /**
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     *
     * <code>optional bool passphrase_protection = 4;</code>
     */
    boolean hasPassphraseProtection();
    /**
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     *
     * <code>optional bool passphrase_protection = 4;</code>
     */
    boolean getPassphraseProtection();

    /**
     * <pre>
     * number of failed PIN attempts
     * </pre>
     *
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     */
    boolean hasPinFailedAttempts();
    /**
     * <pre>
     * number of failed PIN attempts
     * </pre>
     *
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     */
    int getPinFailedAttempts();

    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    boolean hasPin();
    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    java.lang.String getPin();
    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    com.google.protobuf.ByteString
        getPinBytes();

    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    boolean hasLanguage();
    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    boolean hasLabel();
    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    java.lang.String getLabel();
    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <pre>
     * was storage imported from an external source?
     * </pre>
     *
     * <code>optional bool imported = 9;</code>
     */
    boolean hasImported();
    /**
     * <pre>
     * was storage imported from an external source?
     * </pre>
     *
     * <code>optional bool imported = 9;</code>
     */
    boolean getImported();

    /**
     * <pre>
     * image used as homescreen (logo + label is used when not set)
     * </pre>
     *
     * <code>optional bytes homescreen = 10;</code>
     */
    boolean hasHomescreen();
    /**
     * <pre>
     * image used as homescreen (logo + label is used when not set)
     * </pre>
     *
     * <code>optional bytes homescreen = 10;</code>
     */
    com.google.protobuf.ByteString getHomescreen();

    /**
     * <pre>
     * sequence number for u2f authentications
     * </pre>
     *
     * <code>optional uint32 u2f_counter = 11;</code>
     */
    boolean hasU2FCounter();
    /**
     * <pre>
     * sequence number for u2f authentications
     * </pre>
     *
     * <code>optional uint32 u2f_counter = 11;</code>
     */
    int getU2FCounter();

    /**
     * <pre>
     * seed is not backed up yet
     * </pre>
     *
     * <code>optional bool needs_backup = 12;</code>
     */
    boolean hasNeedsBackup();
    /**
     * <pre>
     * seed is not backed up yet
     * </pre>
     *
     * <code>optional bool needs_backup = 12;</code>
     */
    boolean getNeedsBackup();

    /**
     * <pre>
     * device flags
     * </pre>
     *
     * <code>optional uint32 flags = 13;</code>
     */
    boolean hasFlags();
    /**
     * <pre>
     * device flags
     * </pre>
     *
     * <code>optional uint32 flags = 13;</code>
     */
    int getFlags();

    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    boolean hasU2Froot();
    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getU2Froot();
    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getU2FrootOrBuilder();
  }
  /**
   * <pre>
   **
   * Internal persistent storage of device
   * </pre>
   *
   * Protobuf type {@code Storage}
   */
  public  static final class Storage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Storage)
      StorageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Storage() {
      version_ = 0;
      mnemonic_ = "";
      passphraseProtection_ = false;
      pinFailedAttempts_ = 0;
      pin_ = "";
      language_ = "";
      label_ = "";
      imported_ = false;
      homescreen_ = com.google.protobuf.ByteString.EMPTY;
      u2FCounter_ = 0;
      needsBackup_ = false;
      flags_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Storage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 18: {
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = node_.toBuilder();
              }
              node_ = input.readMessage(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(node_);
                node_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mnemonic_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              passphraseProtection_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pinFailedAttempts_ = input.readUInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              pin_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              language_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              label_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              imported_ = input.readBool();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              homescreen_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              u2FCounter_ = input.readUInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              needsBackup_ = input.readBool();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              flags_ = input.readUInt32();
              break;
            }
            case 114: {
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder subBuilder = null;
              if (((bitField0_ & 0x00002000) == 0x00002000)) {
                subBuilder = u2Froot_.toBuilder();
              }
              u2Froot_ = input.readMessage(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(u2Froot_);
                u2Froot_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00002000;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.internal_static_Storage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.internal_static_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.class, com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * version of storage
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * version of storage
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int NODE_FIELD_NUMBER = 2;
    private com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType node_;
    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    public boolean hasNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getNode() {
      return node_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : node_;
    }
    /**
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     *
     * <code>optional .HDNodeType node = 2;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder() {
      return node_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : node_;
    }

    public static final int MNEMONIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object mnemonic_;
    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    public boolean hasMnemonic() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    public java.lang.String getMnemonic() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mnemonic_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     *
     * <code>optional string mnemonic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMnemonicBytes() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnemonic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSPHRASE_PROTECTION_FIELD_NUMBER = 4;
    private boolean passphraseProtection_;
    /**
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     *
     * <code>optional bool passphrase_protection = 4;</code>
     */
    public boolean hasPassphraseProtection() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     *
     * <code>optional bool passphrase_protection = 4;</code>
     */
    public boolean getPassphraseProtection() {
      return passphraseProtection_;
    }

    public static final int PIN_FAILED_ATTEMPTS_FIELD_NUMBER = 5;
    private int pinFailedAttempts_;
    /**
     * <pre>
     * number of failed PIN attempts
     * </pre>
     *
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     */
    public boolean hasPinFailedAttempts() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * number of failed PIN attempts
     * </pre>
     *
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     */
    public int getPinFailedAttempts() {
      return pinFailedAttempts_;
    }

    public static final int PIN_FIELD_NUMBER = 6;
    private volatile java.lang.Object pin_;
    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    public boolean hasPin() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    public java.lang.String getPin() {
      java.lang.Object ref = pin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pin_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * current PIN
     * </pre>
     *
     * <code>optional string pin = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPinBytes() {
      java.lang.Object ref = pin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object language_;
    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * current language
     * </pre>
     *
     * <code>optional string language = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 8;
    private volatile java.lang.Object label_;
    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * device label
     * </pre>
     *
     * <code>optional string label = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMPORTED_FIELD_NUMBER = 9;
    private boolean imported_;
    /**
     * <pre>
     * was storage imported from an external source?
     * </pre>
     *
     * <code>optional bool imported = 9;</code>
     */
    public boolean hasImported() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * was storage imported from an external source?
     * </pre>
     *
     * <code>optional bool imported = 9;</code>
     */
    public boolean getImported() {
      return imported_;
    }

    public static final int HOMESCREEN_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString homescreen_;
    /**
     * <pre>
     * image used as homescreen (logo + label is used when not set)
     * </pre>
     *
     * <code>optional bytes homescreen = 10;</code>
     */
    public boolean hasHomescreen() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     * image used as homescreen (logo + label is used when not set)
     * </pre>
     *
     * <code>optional bytes homescreen = 10;</code>
     */
    public com.google.protobuf.ByteString getHomescreen() {
      return homescreen_;
    }

    public static final int U2F_COUNTER_FIELD_NUMBER = 11;
    private int u2FCounter_;
    /**
     * <pre>
     * sequence number for u2f authentications
     * </pre>
     *
     * <code>optional uint32 u2f_counter = 11;</code>
     */
    public boolean hasU2FCounter() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     * sequence number for u2f authentications
     * </pre>
     *
     * <code>optional uint32 u2f_counter = 11;</code>
     */
    public int getU2FCounter() {
      return u2FCounter_;
    }

    public static final int NEEDS_BACKUP_FIELD_NUMBER = 12;
    private boolean needsBackup_;
    /**
     * <pre>
     * seed is not backed up yet
     * </pre>
     *
     * <code>optional bool needs_backup = 12;</code>
     */
    public boolean hasNeedsBackup() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * seed is not backed up yet
     * </pre>
     *
     * <code>optional bool needs_backup = 12;</code>
     */
    public boolean getNeedsBackup() {
      return needsBackup_;
    }

    public static final int FLAGS_FIELD_NUMBER = 13;
    private int flags_;
    /**
     * <pre>
     * device flags
     * </pre>
     *
     * <code>optional uint32 flags = 13;</code>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <pre>
     * device flags
     * </pre>
     *
     * <code>optional uint32 flags = 13;</code>
     */
    public int getFlags() {
      return flags_;
    }

    public static final int U2FROOT_FIELD_NUMBER = 14;
    private com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType u2Froot_;
    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    public boolean hasU2Froot() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getU2Froot() {
      return u2Froot_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : u2Froot_;
    }
    /**
     * <pre>
     * U2F root node
     * </pre>
     *
     * <code>optional .HDNodeType u2froot = 14;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getU2FrootOrBuilder() {
      return u2Froot_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : u2Froot_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasNode()) {
        if (!getNode().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasU2Froot()) {
        if (!getU2Froot().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getNode());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mnemonic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, passphraseProtection_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, pinFailedAttempts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pin_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, language_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, label_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, imported_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, homescreen_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, u2FCounter_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, needsBackup_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(13, flags_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeMessage(14, getU2Froot());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNode());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mnemonic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, passphraseProtection_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, pinFailedAttempts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pin_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, language_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, label_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, imported_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, homescreen_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, u2FCounter_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, needsBackup_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, flags_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getU2Froot());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage)) {
        return super.equals(obj);
      }
      com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage other = (com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasNode() == other.hasNode());
      if (hasNode()) {
        result = result && getNode()
            .equals(other.getNode());
      }
      result = result && (hasMnemonic() == other.hasMnemonic());
      if (hasMnemonic()) {
        result = result && getMnemonic()
            .equals(other.getMnemonic());
      }
      result = result && (hasPassphraseProtection() == other.hasPassphraseProtection());
      if (hasPassphraseProtection()) {
        result = result && (getPassphraseProtection()
            == other.getPassphraseProtection());
      }
      result = result && (hasPinFailedAttempts() == other.hasPinFailedAttempts());
      if (hasPinFailedAttempts()) {
        result = result && (getPinFailedAttempts()
            == other.getPinFailedAttempts());
      }
      result = result && (hasPin() == other.hasPin());
      if (hasPin()) {
        result = result && getPin()
            .equals(other.getPin());
      }
      result = result && (hasLanguage() == other.hasLanguage());
      if (hasLanguage()) {
        result = result && getLanguage()
            .equals(other.getLanguage());
      }
      result = result && (hasLabel() == other.hasLabel());
      if (hasLabel()) {
        result = result && getLabel()
            .equals(other.getLabel());
      }
      result = result && (hasImported() == other.hasImported());
      if (hasImported()) {
        result = result && (getImported()
            == other.getImported());
      }
      result = result && (hasHomescreen() == other.hasHomescreen());
      if (hasHomescreen()) {
        result = result && getHomescreen()
            .equals(other.getHomescreen());
      }
      result = result && (hasU2FCounter() == other.hasU2FCounter());
      if (hasU2FCounter()) {
        result = result && (getU2FCounter()
            == other.getU2FCounter());
      }
      result = result && (hasNeedsBackup() == other.hasNeedsBackup());
      if (hasNeedsBackup()) {
        result = result && (getNeedsBackup()
            == other.getNeedsBackup());
      }
      result = result && (hasFlags() == other.hasFlags());
      if (hasFlags()) {
        result = result && (getFlags()
            == other.getFlags());
      }
      result = result && (hasU2Froot() == other.hasU2Froot());
      if (hasU2Froot()) {
        result = result && getU2Froot()
            .equals(other.getU2Froot());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasNode()) {
        hash = (37 * hash) + NODE_FIELD_NUMBER;
        hash = (53 * hash) + getNode().hashCode();
      }
      if (hasMnemonic()) {
        hash = (37 * hash) + MNEMONIC_FIELD_NUMBER;
        hash = (53 * hash) + getMnemonic().hashCode();
      }
      if (hasPassphraseProtection()) {
        hash = (37 * hash) + PASSPHRASE_PROTECTION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPassphraseProtection());
      }
      if (hasPinFailedAttempts()) {
        hash = (37 * hash) + PIN_FAILED_ATTEMPTS_FIELD_NUMBER;
        hash = (53 * hash) + getPinFailedAttempts();
      }
      if (hasPin()) {
        hash = (37 * hash) + PIN_FIELD_NUMBER;
        hash = (53 * hash) + getPin().hashCode();
      }
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage().hashCode();
      }
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      if (hasImported()) {
        hash = (37 * hash) + IMPORTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getImported());
      }
      if (hasHomescreen()) {
        hash = (37 * hash) + HOMESCREEN_FIELD_NUMBER;
        hash = (53 * hash) + getHomescreen().hashCode();
      }
      if (hasU2FCounter()) {
        hash = (37 * hash) + U2F_COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + getU2FCounter();
      }
      if (hasNeedsBackup()) {
        hash = (37 * hash) + NEEDS_BACKUP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNeedsBackup());
      }
      if (hasFlags()) {
        hash = (37 * hash) + FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getFlags();
      }
      if (hasU2Froot()) {
        hash = (37 * hash) + U2FROOT_FIELD_NUMBER;
        hash = (53 * hash) + getU2Froot().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Internal persistent storage of device
     * </pre>
     *
     * Protobuf type {@code Storage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Storage)
        com.satoshilabs.trezor.lib.protobuf.TrezorStorage.StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.internal_static_Storage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.internal_static_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.class, com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.Builder.class);
      }

      // Construct using com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeFieldBuilder();
          getU2FrootFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nodeBuilder_ == null) {
          node_ = null;
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        mnemonic_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        passphraseProtection_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        pinFailedAttempts_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        pin_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        language_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        imported_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        homescreen_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        u2FCounter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        needsBackup_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        if (u2FrootBuilder_ == null) {
          u2Froot_ = null;
        } else {
          u2FrootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.internal_static_Storage_descriptor;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage getDefaultInstanceForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.getDefaultInstance();
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage build() {
        com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage buildPartial() {
        com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage result = new com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (nodeBuilder_ == null) {
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mnemonic_ = mnemonic_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.passphraseProtection_ = passphraseProtection_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pinFailedAttempts_ = pinFailedAttempts_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pin_ = pin_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.imported_ = imported_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.homescreen_ = homescreen_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.u2FCounter_ = u2FCounter_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.needsBackup_ = needsBackup_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        if (u2FrootBuilder_ == null) {
          result.u2Froot_ = u2Froot_;
        } else {
          result.u2Froot_ = u2FrootBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage) {
          return mergeFrom((com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage other) {
        if (other == com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasMnemonic()) {
          bitField0_ |= 0x00000004;
          mnemonic_ = other.mnemonic_;
          onChanged();
        }
        if (other.hasPassphraseProtection()) {
          setPassphraseProtection(other.getPassphraseProtection());
        }
        if (other.hasPinFailedAttempts()) {
          setPinFailedAttempts(other.getPinFailedAttempts());
        }
        if (other.hasPin()) {
          bitField0_ |= 0x00000020;
          pin_ = other.pin_;
          onChanged();
        }
        if (other.hasLanguage()) {
          bitField0_ |= 0x00000040;
          language_ = other.language_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000080;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasImported()) {
          setImported(other.getImported());
        }
        if (other.hasHomescreen()) {
          setHomescreen(other.getHomescreen());
        }
        if (other.hasU2FCounter()) {
          setU2FCounter(other.getU2FCounter());
        }
        if (other.hasNeedsBackup()) {
          setNeedsBackup(other.getNeedsBackup());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasU2Froot()) {
          mergeU2Froot(other.getU2Froot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (hasNode()) {
          if (!getNode().isInitialized()) {
            return false;
          }
        }
        if (hasU2Froot()) {
          if (!getU2Froot().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       * version of storage
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * version of storage
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * version of storage
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version of storage
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType node_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder> nodeBuilder_;
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public boolean hasNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getNode() {
        if (nodeBuilder_ == null) {
          return node_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : node_;
        } else {
          return nodeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public Builder setNode(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          nodeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public Builder setNode(
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          nodeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public Builder mergeNode(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType value) {
        if (nodeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              node_ != null &&
              node_ != com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance()) {
            node_ =
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.newBuilder(node_).mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          nodeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = null;
          onChanged();
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder getNodeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNodeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilder();
        } else {
          return node_ == null ?
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : node_;
        }
      }
      /**
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       *
       * <code>optional .HDNodeType node = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder>(
                  getNode(),
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }

      private java.lang.Object mnemonic_ = "";
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public boolean hasMnemonic() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public java.lang.String getMnemonic() {
        java.lang.Object ref = mnemonic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mnemonic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMnemonicBytes() {
        java.lang.Object ref = mnemonic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnemonic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public Builder setMnemonic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mnemonic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public Builder clearMnemonic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mnemonic_ = getDefaultInstance().getMnemonic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       *
       * <code>optional string mnemonic = 3;</code>
       */
      public Builder setMnemonicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mnemonic_ = value;
        onChanged();
        return this;
      }

      private boolean passphraseProtection_ ;
      /**
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       *
       * <code>optional bool passphrase_protection = 4;</code>
       */
      public boolean hasPassphraseProtection() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       *
       * <code>optional bool passphrase_protection = 4;</code>
       */
      public boolean getPassphraseProtection() {
        return passphraseProtection_;
      }
      /**
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       *
       * <code>optional bool passphrase_protection = 4;</code>
       */
      public Builder setPassphraseProtection(boolean value) {
        bitField0_ |= 0x00000008;
        passphraseProtection_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       *
       * <code>optional bool passphrase_protection = 4;</code>
       */
      public Builder clearPassphraseProtection() {
        bitField0_ = (bitField0_ & ~0x00000008);
        passphraseProtection_ = false;
        onChanged();
        return this;
      }

      private int pinFailedAttempts_ ;
      /**
       * <pre>
       * number of failed PIN attempts
       * </pre>
       *
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       */
      public boolean hasPinFailedAttempts() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * number of failed PIN attempts
       * </pre>
       *
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       */
      public int getPinFailedAttempts() {
        return pinFailedAttempts_;
      }
      /**
       * <pre>
       * number of failed PIN attempts
       * </pre>
       *
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       */
      public Builder setPinFailedAttempts(int value) {
        bitField0_ |= 0x00000010;
        pinFailedAttempts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * number of failed PIN attempts
       * </pre>
       *
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       */
      public Builder clearPinFailedAttempts() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pinFailedAttempts_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pin_ = "";
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public boolean hasPin() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public java.lang.String getPin() {
        java.lang.Object ref = pin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPinBytes() {
        java.lang.Object ref = pin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public Builder setPin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public Builder clearPin() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pin_ = getDefaultInstance().getPin();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * current PIN
       * </pre>
       *
       * <code>optional string pin = 6;</code>
       */
      public Builder setPinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000040);
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * current language
       * </pre>
       *
       * <code>optional string language = 7;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            label_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000080);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * device label
       * </pre>
       *
       * <code>optional string label = 8;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        label_ = value;
        onChanged();
        return this;
      }

      private boolean imported_ ;
      /**
       * <pre>
       * was storage imported from an external source?
       * </pre>
       *
       * <code>optional bool imported = 9;</code>
       */
      public boolean hasImported() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * was storage imported from an external source?
       * </pre>
       *
       * <code>optional bool imported = 9;</code>
       */
      public boolean getImported() {
        return imported_;
      }
      /**
       * <pre>
       * was storage imported from an external source?
       * </pre>
       *
       * <code>optional bool imported = 9;</code>
       */
      public Builder setImported(boolean value) {
        bitField0_ |= 0x00000100;
        imported_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * was storage imported from an external source?
       * </pre>
       *
       * <code>optional bool imported = 9;</code>
       */
      public Builder clearImported() {
        bitField0_ = (bitField0_ & ~0x00000100);
        imported_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString homescreen_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * image used as homescreen (logo + label is used when not set)
       * </pre>
       *
       * <code>optional bytes homescreen = 10;</code>
       */
      public boolean hasHomescreen() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       * image used as homescreen (logo + label is used when not set)
       * </pre>
       *
       * <code>optional bytes homescreen = 10;</code>
       */
      public com.google.protobuf.ByteString getHomescreen() {
        return homescreen_;
      }
      /**
       * <pre>
       * image used as homescreen (logo + label is used when not set)
       * </pre>
       *
       * <code>optional bytes homescreen = 10;</code>
       */
      public Builder setHomescreen(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        homescreen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * image used as homescreen (logo + label is used when not set)
       * </pre>
       *
       * <code>optional bytes homescreen = 10;</code>
       */
      public Builder clearHomescreen() {
        bitField0_ = (bitField0_ & ~0x00000200);
        homescreen_ = getDefaultInstance().getHomescreen();
        onChanged();
        return this;
      }

      private int u2FCounter_ ;
      /**
       * <pre>
       * sequence number for u2f authentications
       * </pre>
       *
       * <code>optional uint32 u2f_counter = 11;</code>
       */
      public boolean hasU2FCounter() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       * sequence number for u2f authentications
       * </pre>
       *
       * <code>optional uint32 u2f_counter = 11;</code>
       */
      public int getU2FCounter() {
        return u2FCounter_;
      }
      /**
       * <pre>
       * sequence number for u2f authentications
       * </pre>
       *
       * <code>optional uint32 u2f_counter = 11;</code>
       */
      public Builder setU2FCounter(int value) {
        bitField0_ |= 0x00000400;
        u2FCounter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sequence number for u2f authentications
       * </pre>
       *
       * <code>optional uint32 u2f_counter = 11;</code>
       */
      public Builder clearU2FCounter() {
        bitField0_ = (bitField0_ & ~0x00000400);
        u2FCounter_ = 0;
        onChanged();
        return this;
      }

      private boolean needsBackup_ ;
      /**
       * <pre>
       * seed is not backed up yet
       * </pre>
       *
       * <code>optional bool needs_backup = 12;</code>
       */
      public boolean hasNeedsBackup() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * seed is not backed up yet
       * </pre>
       *
       * <code>optional bool needs_backup = 12;</code>
       */
      public boolean getNeedsBackup() {
        return needsBackup_;
      }
      /**
       * <pre>
       * seed is not backed up yet
       * </pre>
       *
       * <code>optional bool needs_backup = 12;</code>
       */
      public Builder setNeedsBackup(boolean value) {
        bitField0_ |= 0x00000800;
        needsBackup_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seed is not backed up yet
       * </pre>
       *
       * <code>optional bool needs_backup = 12;</code>
       */
      public Builder clearNeedsBackup() {
        bitField0_ = (bitField0_ & ~0x00000800);
        needsBackup_ = false;
        onChanged();
        return this;
      }

      private int flags_ ;
      /**
       * <pre>
       * device flags
       * </pre>
       *
       * <code>optional uint32 flags = 13;</code>
       */
      public boolean hasFlags() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       * device flags
       * </pre>
       *
       * <code>optional uint32 flags = 13;</code>
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <pre>
       * device flags
       * </pre>
       *
       * <code>optional uint32 flags = 13;</code>
       */
      public Builder setFlags(int value) {
        bitField0_ |= 0x00001000;
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * device flags
       * </pre>
       *
       * <code>optional uint32 flags = 13;</code>
       */
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00001000);
        flags_ = 0;
        onChanged();
        return this;
      }

      private com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType u2Froot_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder> u2FrootBuilder_;
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public boolean hasU2Froot() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType getU2Froot() {
        if (u2FrootBuilder_ == null) {
          return u2Froot_ == null ? com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : u2Froot_;
        } else {
          return u2FrootBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public Builder setU2Froot(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType value) {
        if (u2FrootBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          u2Froot_ = value;
          onChanged();
        } else {
          u2FrootBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public Builder setU2Froot(
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder builderForValue) {
        if (u2FrootBuilder_ == null) {
          u2Froot_ = builderForValue.build();
          onChanged();
        } else {
          u2FrootBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public Builder mergeU2Froot(com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType value) {
        if (u2FrootBuilder_ == null) {
          if (((bitField0_ & 0x00002000) == 0x00002000) &&
              u2Froot_ != null &&
              u2Froot_ != com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance()) {
            u2Froot_ =
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.newBuilder(u2Froot_).mergeFrom(value).buildPartial();
          } else {
            u2Froot_ = value;
          }
          onChanged();
        } else {
          u2FrootBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00002000;
        return this;
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public Builder clearU2Froot() {
        if (u2FrootBuilder_ == null) {
          u2Froot_ = null;
          onChanged();
        } else {
          u2FrootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder getU2FrootBuilder() {
        bitField0_ |= 0x00002000;
        onChanged();
        return getU2FrootFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder getU2FrootOrBuilder() {
        if (u2FrootBuilder_ != null) {
          return u2FrootBuilder_.getMessageOrBuilder();
        } else {
          return u2Froot_ == null ?
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.getDefaultInstance() : u2Froot_;
        }
      }
      /**
       * <pre>
       * U2F root node
       * </pre>
       *
       * <code>optional .HDNodeType u2froot = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder> 
          getU2FrootFieldBuilder() {
        if (u2FrootBuilder_ == null) {
          u2FrootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorType.HDNodeTypeOrBuilder>(
                  getU2Froot(),
                  getParentForChildren(),
                  isClean());
          u2Froot_ = null;
        }
        return u2FrootBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Storage)
    }

    // @@protoc_insertion_point(class_scope:Storage)
    private static final com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage();
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Storage>
        PARSER = new com.google.protobuf.AbstractParser<Storage>() {
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Storage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Storage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    public com.satoshilabs.trezor.lib.protobuf.TrezorStorage.Storage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstorage.proto\032\013types.proto\"\257\002\n\007Storage" +
      "\022\017\n\007version\030\001 \002(\r\022\031\n\004node\030\002 \001(\0132\013.HDNode" +
      "Type\022\020\n\010mnemonic\030\003 \001(\t\022\035\n\025passphrase_pro" +
      "tection\030\004 \001(\010\022\033\n\023pin_failed_attempts\030\005 \001" +
      "(\r\022\013\n\003pin\030\006 \001(\t\022\020\n\010language\030\007 \001(\t\022\r\n\005lab" +
      "el\030\010 \001(\t\022\020\n\010imported\030\t \001(\010\022\022\n\nhomescreen" +
      "\030\n \001(\014\022\023\n\013u2f_counter\030\013 \001(\r\022\024\n\014needs_bac" +
      "kup\030\014 \001(\010\022\r\n\005flags\030\r \001(\r\022\034\n\007u2froot\030\016 \001(" +
      "\0132\013.HDNodeTypeB4\n#com.satoshilabs.trezor" +
      ".lib.protobufB\rTrezorStorage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.satoshilabs.trezor.lib.protobuf.TrezorType.getDescriptor(),
        }, assigner);
    internal_static_Storage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Storage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_descriptor,
        new java.lang.String[] { "Version", "Node", "Mnemonic", "PassphraseProtection", "PinFailedAttempts", "Pin", "Language", "Label", "Imported", "Homescreen", "U2FCounter", "NeedsBackup", "Flags", "U2Froot", });
    com.satoshilabs.trezor.lib.protobuf.TrezorType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
