// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package com.satoshilabs.trezor.lib.protobuf;

public final class TrezorConfig {
  private TrezorConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * USB vendor ID
     * </pre>
     *
     * <code>optional uint32 vendor_id = 1;</code>
     */
    boolean hasVendorId();
    /**
     * <pre>
     * USB vendor ID
     * </pre>
     *
     * <code>optional uint32 vendor_id = 1;</code>
     */
    int getVendorId();

    /**
     * <pre>
     * USB product ID
     * </pre>
     *
     * <code>optional uint32 product_id = 2;</code>
     */
    boolean hasProductId();
    /**
     * <pre>
     * USB product ID
     * </pre>
     *
     * <code>optional uint32 product_id = 2;</code>
     */
    int getProductId();

    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    boolean hasSerialNumber();
    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    java.lang.String getSerialNumber();
    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    com.google.protobuf.ByteString
        getSerialNumberBytes();

    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    boolean hasPath();
    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * <pre>
   **
   * Device Descriptor used in Configuration
   * </pre>
   *
   * Protobuf type {@code DeviceDescriptor}
   */
  public  static final class DeviceDescriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeviceDescriptor)
      DeviceDescriptorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceDescriptor.newBuilder() to construct.
    private DeviceDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceDescriptor() {
      vendorId_ = 0;
      productId_ = 0;
      serialNumber_ = "";
      path_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              vendorId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              productId_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              serialNumber_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              path_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_DeviceDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_DeviceDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.class, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder.class);
    }

    private int bitField0_;
    public static final int VENDOR_ID_FIELD_NUMBER = 1;
    private int vendorId_;
    /**
     * <pre>
     * USB vendor ID
     * </pre>
     *
     * <code>optional uint32 vendor_id = 1;</code>
     */
    public boolean hasVendorId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * USB vendor ID
     * </pre>
     *
     * <code>optional uint32 vendor_id = 1;</code>
     */
    public int getVendorId() {
      return vendorId_;
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 2;
    private int productId_;
    /**
     * <pre>
     * USB product ID
     * </pre>
     *
     * <code>optional uint32 product_id = 2;</code>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * USB product ID
     * </pre>
     *
     * <code>optional uint32 product_id = 2;</code>
     */
    public int getProductId() {
      return productId_;
    }

    public static final int SERIAL_NUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object serialNumber_;
    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    public boolean hasSerialNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    public java.lang.String getSerialNumber() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serialNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * USB serial number
     * </pre>
     *
     * <code>optional string serial_number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * USB device path
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, vendorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serialNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, path_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, vendorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, productId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serialNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor)) {
        return super.equals(obj);
      }
      com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor other = (com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor) obj;

      boolean result = true;
      result = result && (hasVendorId() == other.hasVendorId());
      if (hasVendorId()) {
        result = result && (getVendorId()
            == other.getVendorId());
      }
      result = result && (hasProductId() == other.hasProductId());
      if (hasProductId()) {
        result = result && (getProductId()
            == other.getProductId());
      }
      result = result && (hasSerialNumber() == other.hasSerialNumber());
      if (hasSerialNumber()) {
        result = result && getSerialNumber()
            .equals(other.getSerialNumber());
      }
      result = result && (hasPath() == other.hasPath());
      if (hasPath()) {
        result = result && getPath()
            .equals(other.getPath());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVendorId()) {
        hash = (37 * hash) + VENDOR_ID_FIELD_NUMBER;
        hash = (53 * hash) + getVendorId();
      }
      if (hasProductId()) {
        hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getProductId();
      }
      if (hasSerialNumber()) {
        hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getSerialNumber().hashCode();
      }
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Device Descriptor used in Configuration
     * </pre>
     *
     * Protobuf type {@code DeviceDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceDescriptor)
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_DeviceDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_DeviceDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.class, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder.class);
      }

      // Construct using com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        vendorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serialNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_DeviceDescriptor_descriptor;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getDefaultInstanceForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.getDefaultInstance();
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor build() {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor buildPartial() {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor result = new com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vendorId_ = vendorId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serialNumber_ = serialNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor) {
          return mergeFrom((com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor other) {
        if (other == com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.getDefaultInstance()) return this;
        if (other.hasVendorId()) {
          setVendorId(other.getVendorId());
        }
        if (other.hasProductId()) {
          setProductId(other.getProductId());
        }
        if (other.hasSerialNumber()) {
          bitField0_ |= 0x00000004;
          serialNumber_ = other.serialNumber_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000008;
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int vendorId_ ;
      /**
       * <pre>
       * USB vendor ID
       * </pre>
       *
       * <code>optional uint32 vendor_id = 1;</code>
       */
      public boolean hasVendorId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * USB vendor ID
       * </pre>
       *
       * <code>optional uint32 vendor_id = 1;</code>
       */
      public int getVendorId() {
        return vendorId_;
      }
      /**
       * <pre>
       * USB vendor ID
       * </pre>
       *
       * <code>optional uint32 vendor_id = 1;</code>
       */
      public Builder setVendorId(int value) {
        bitField0_ |= 0x00000001;
        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB vendor ID
       * </pre>
       *
       * <code>optional uint32 vendor_id = 1;</code>
       */
      public Builder clearVendorId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vendorId_ = 0;
        onChanged();
        return this;
      }

      private int productId_ ;
      /**
       * <pre>
       * USB product ID
       * </pre>
       *
       * <code>optional uint32 product_id = 2;</code>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * USB product ID
       * </pre>
       *
       * <code>optional uint32 product_id = 2;</code>
       */
      public int getProductId() {
        return productId_;
      }
      /**
       * <pre>
       * USB product ID
       * </pre>
       *
       * <code>optional uint32 product_id = 2;</code>
       */
      public Builder setProductId(int value) {
        bitField0_ |= 0x00000002;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB product ID
       * </pre>
       *
       * <code>optional uint32 product_id = 2;</code>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        productId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serialNumber_ = "";
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public boolean hasSerialNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public java.lang.String getSerialNumber() {
        java.lang.Object ref = serialNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serialNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNumberBytes() {
        java.lang.Object ref = serialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public Builder setSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public Builder clearSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serialNumber_ = getDefaultInstance().getSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB serial number
       * </pre>
       *
       * <code>optional string serial_number = 3;</code>
       */
      public Builder setSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serialNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * USB device path
       * </pre>
       *
       * <code>optional string path = 4;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeviceDescriptor)
    }

    // @@protoc_insertion_point(class_scope:DeviceDescriptor)
    private static final com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor();
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DeviceDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<DeviceDescriptor>() {
      public DeviceDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceDescriptor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceDescriptor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceDescriptor> getParserForType() {
      return PARSER;
    }

    public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Configuration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    java.util.List<java.lang.String>
        getWhitelistUrlsList();
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    int getWhitelistUrlsCount();
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    java.lang.String getWhitelistUrls(int index);
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    com.google.protobuf.ByteString
        getWhitelistUrlsBytes(int index);

    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    java.util.List<java.lang.String>
        getBlacklistUrlsList();
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    int getBlacklistUrlsCount();
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    java.lang.String getBlacklistUrls(int index);
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    com.google.protobuf.ByteString
        getBlacklistUrlsBytes(int index);

    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    boolean hasWireProtocol();
    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol();
    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder();

    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> 
        getKnownDevicesList();
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getKnownDevices(int index);
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    int getKnownDevicesCount();
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    java.util.List<? extends com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder> 
        getKnownDevicesOrBuilderList();
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
        int index);

    /**
     * <pre>
     * expiration timestamp
     * </pre>
     *
     * <code>optional uint32 valid_until = 5;</code>
     */
    boolean hasValidUntil();
    /**
     * <pre>
     * expiration timestamp
     * </pre>
     *
     * <code>optional uint32 valid_until = 5;</code>
     */
    int getValidUntil();
  }
  /**
   * <pre>
   **
   * Plugin Configuration
   * </pre>
   *
   * Protobuf type {@code Configuration}
   */
  public  static final class Configuration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Configuration)
      ConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Configuration() {
      whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      knownDevices_ = java.util.Collections.emptyList();
      validUntil_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Configuration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                whitelistUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              whitelistUrls_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                blacklistUrls_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              blacklistUrls_.add(bs);
              break;
            }
            case 26: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = wireProtocol_.toBuilder();
              }
              wireProtocol_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wireProtocol_);
                wireProtocol_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                knownDevices_ = new java.util.ArrayList<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor>();
                mutable_bitField0_ |= 0x00000008;
              }
              knownDevices_.add(
                  input.readMessage(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              validUntil_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = whitelistUrls_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = blacklistUrls_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          knownDevices_ = java.util.Collections.unmodifiableList(knownDevices_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_Configuration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.class, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.Builder.class);
    }

    private int bitField0_;
    public static final int WHITELIST_URLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList whitelistUrls_;
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getWhitelistUrlsList() {
      return whitelistUrls_;
    }
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    public int getWhitelistUrlsCount() {
      return whitelistUrls_.size();
    }
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    public java.lang.String getWhitelistUrls(int index) {
      return whitelistUrls_.get(index);
    }
    /**
     * <pre>
     * allowed URLs for plugin
     * </pre>
     *
     * <code>repeated string whitelist_urls = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWhitelistUrlsBytes(int index) {
      return whitelistUrls_.getByteString(index);
    }

    public static final int BLACKLIST_URLS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList blacklistUrls_;
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBlacklistUrlsList() {
      return blacklistUrls_;
    }
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    public int getBlacklistUrlsCount() {
      return blacklistUrls_.size();
    }
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    public java.lang.String getBlacklistUrls(int index) {
      return blacklistUrls_.get(index);
    }
    /**
     * <pre>
     * forbidden URLs for plugin
     * </pre>
     *
     * <code>repeated string blacklist_urls = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBlacklistUrlsBytes(int index) {
      return blacklistUrls_.getByteString(index);
    }

    public static final int WIRE_PROTOCOL_FIELD_NUMBER = 3;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet wireProtocol_;
    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    public boolean hasWireProtocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol() {
      return wireProtocol_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : wireProtocol_;
    }
    /**
     * <pre>
     * compiled specification of write protocol (serialized using "protoc -o")
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder() {
      return wireProtocol_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : wireProtocol_;
    }

    public static final int KNOWN_DEVICES_FIELD_NUMBER = 4;
    private java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> knownDevices_;
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    public java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> getKnownDevicesList() {
      return knownDevices_;
    }
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    public java.util.List<? extends com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder> 
        getKnownDevicesOrBuilderList() {
      return knownDevices_;
    }
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    public int getKnownDevicesCount() {
      return knownDevices_.size();
    }
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getKnownDevices(int index) {
      return knownDevices_.get(index);
    }
    /**
     * <pre>
     * descriptors of allowed devices
     * </pre>
     *
     * <code>repeated .DeviceDescriptor known_devices = 4;</code>
     */
    public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
        int index) {
      return knownDevices_.get(index);
    }

    public static final int VALID_UNTIL_FIELD_NUMBER = 5;
    private int validUntil_;
    /**
     * <pre>
     * expiration timestamp
     * </pre>
     *
     * <code>optional uint32 valid_until = 5;</code>
     */
    public boolean hasValidUntil() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * expiration timestamp
     * </pre>
     *
     * <code>optional uint32 valid_until = 5;</code>
     */
    public int getValidUntil() {
      return validUntil_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWireProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getWireProtocol().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < whitelistUrls_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, whitelistUrls_.getRaw(i));
      }
      for (int i = 0; i < blacklistUrls_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blacklistUrls_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(3, getWireProtocol());
      }
      for (int i = 0; i < knownDevices_.size(); i++) {
        output.writeMessage(4, knownDevices_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(5, validUntil_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < whitelistUrls_.size(); i++) {
          dataSize += computeStringSizeNoTag(whitelistUrls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getWhitelistUrlsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blacklistUrls_.size(); i++) {
          dataSize += computeStringSizeNoTag(blacklistUrls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBlacklistUrlsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWireProtocol());
      }
      for (int i = 0; i < knownDevices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, knownDevices_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, validUntil_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration)) {
        return super.equals(obj);
      }
      com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration other = (com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration) obj;

      boolean result = true;
      result = result && getWhitelistUrlsList()
          .equals(other.getWhitelistUrlsList());
      result = result && getBlacklistUrlsList()
          .equals(other.getBlacklistUrlsList());
      result = result && (hasWireProtocol() == other.hasWireProtocol());
      if (hasWireProtocol()) {
        result = result && getWireProtocol()
            .equals(other.getWireProtocol());
      }
      result = result && getKnownDevicesList()
          .equals(other.getKnownDevicesList());
      result = result && (hasValidUntil() == other.hasValidUntil());
      if (hasValidUntil()) {
        result = result && (getValidUntil()
            == other.getValidUntil());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWhitelistUrlsCount() > 0) {
        hash = (37 * hash) + WHITELIST_URLS_FIELD_NUMBER;
        hash = (53 * hash) + getWhitelistUrlsList().hashCode();
      }
      if (getBlacklistUrlsCount() > 0) {
        hash = (37 * hash) + BLACKLIST_URLS_FIELD_NUMBER;
        hash = (53 * hash) + getBlacklistUrlsList().hashCode();
      }
      if (hasWireProtocol()) {
        hash = (37 * hash) + WIRE_PROTOCOL_FIELD_NUMBER;
        hash = (53 * hash) + getWireProtocol().hashCode();
      }
      if (getKnownDevicesCount() > 0) {
        hash = (37 * hash) + KNOWN_DEVICES_FIELD_NUMBER;
        hash = (53 * hash) + getKnownDevicesList().hashCode();
      }
      if (hasValidUntil()) {
        hash = (37 * hash) + VALID_UNTIL_FIELD_NUMBER;
        hash = (53 * hash) + getValidUntil();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Plugin Configuration
     * </pre>
     *
     * Protobuf type {@code Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Configuration)
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_Configuration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.class, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.Builder.class);
      }

      // Construct using com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWireProtocolFieldBuilder();
          getKnownDevicesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = null;
        } else {
          wireProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (knownDevicesBuilder_ == null) {
          knownDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          knownDevicesBuilder_.clear();
        }
        validUntil_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.internal_static_Configuration_descriptor;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration getDefaultInstanceForType() {
        return com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.getDefaultInstance();
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration build() {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration buildPartial() {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration result = new com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = whitelistUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.whitelistUrls_ = whitelistUrls_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = blacklistUrls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.blacklistUrls_ = blacklistUrls_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        if (wireProtocolBuilder_ == null) {
          result.wireProtocol_ = wireProtocol_;
        } else {
          result.wireProtocol_ = wireProtocolBuilder_.build();
        }
        if (knownDevicesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            knownDevices_ = java.util.Collections.unmodifiableList(knownDevices_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.knownDevices_ = knownDevices_;
        } else {
          result.knownDevices_ = knownDevicesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000002;
        }
        result.validUntil_ = validUntil_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration) {
          return mergeFrom((com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration other) {
        if (other == com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration.getDefaultInstance()) return this;
        if (!other.whitelistUrls_.isEmpty()) {
          if (whitelistUrls_.isEmpty()) {
            whitelistUrls_ = other.whitelistUrls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWhitelistUrlsIsMutable();
            whitelistUrls_.addAll(other.whitelistUrls_);
          }
          onChanged();
        }
        if (!other.blacklistUrls_.isEmpty()) {
          if (blacklistUrls_.isEmpty()) {
            blacklistUrls_ = other.blacklistUrls_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBlacklistUrlsIsMutable();
            blacklistUrls_.addAll(other.blacklistUrls_);
          }
          onChanged();
        }
        if (other.hasWireProtocol()) {
          mergeWireProtocol(other.getWireProtocol());
        }
        if (knownDevicesBuilder_ == null) {
          if (!other.knownDevices_.isEmpty()) {
            if (knownDevices_.isEmpty()) {
              knownDevices_ = other.knownDevices_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureKnownDevicesIsMutable();
              knownDevices_.addAll(other.knownDevices_);
            }
            onChanged();
          }
        } else {
          if (!other.knownDevices_.isEmpty()) {
            if (knownDevicesBuilder_.isEmpty()) {
              knownDevicesBuilder_.dispose();
              knownDevicesBuilder_ = null;
              knownDevices_ = other.knownDevices_;
              bitField0_ = (bitField0_ & ~0x00000008);
              knownDevicesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKnownDevicesFieldBuilder() : null;
            } else {
              knownDevicesBuilder_.addAllMessages(other.knownDevices_);
            }
          }
        }
        if (other.hasValidUntil()) {
          setValidUntil(other.getValidUntil());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWireProtocol()) {
          return false;
        }
        if (!getWireProtocol().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWhitelistUrlsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          whitelistUrls_ = new com.google.protobuf.LazyStringArrayList(whitelistUrls_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getWhitelistUrlsList() {
        return whitelistUrls_.getUnmodifiableView();
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public int getWhitelistUrlsCount() {
        return whitelistUrls_.size();
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public java.lang.String getWhitelistUrls(int index) {
        return whitelistUrls_.get(index);
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWhitelistUrlsBytes(int index) {
        return whitelistUrls_.getByteString(index);
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public Builder setWhitelistUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public Builder addWhitelistUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public Builder addAllWhitelistUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureWhitelistUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, whitelistUrls_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public Builder clearWhitelistUrls() {
        whitelistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * allowed URLs for plugin
       * </pre>
       *
       * <code>repeated string whitelist_urls = 1;</code>
       */
      public Builder addWhitelistUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWhitelistUrlsIsMutable();
        whitelistUrls_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBlacklistUrlsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          blacklistUrls_ = new com.google.protobuf.LazyStringArrayList(blacklistUrls_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBlacklistUrlsList() {
        return blacklistUrls_.getUnmodifiableView();
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public int getBlacklistUrlsCount() {
        return blacklistUrls_.size();
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public java.lang.String getBlacklistUrls(int index) {
        return blacklistUrls_.get(index);
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBlacklistUrlsBytes(int index) {
        return blacklistUrls_.getByteString(index);
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public Builder setBlacklistUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public Builder addBlacklistUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public Builder addAllBlacklistUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureBlacklistUrlsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blacklistUrls_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public Builder clearBlacklistUrls() {
        blacklistUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * forbidden URLs for plugin
       * </pre>
       *
       * <code>repeated string blacklist_urls = 2;</code>
       */
      public Builder addBlacklistUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlacklistUrlsIsMutable();
        blacklistUrls_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet wireProtocol_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> wireProtocolBuilder_;
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public boolean hasWireProtocol() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getWireProtocol() {
        if (wireProtocolBuilder_ == null) {
          return wireProtocol_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : wireProtocol_;
        } else {
          return wireProtocolBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public Builder setWireProtocol(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (wireProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wireProtocol_ = value;
          onChanged();
        } else {
          wireProtocolBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public Builder setWireProtocol(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = builderForValue.build();
          onChanged();
        } else {
          wireProtocolBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public Builder mergeWireProtocol(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (wireProtocolBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              wireProtocol_ != null &&
              wireProtocol_ != com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance()) {
            wireProtocol_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(wireProtocol_).mergeFrom(value).buildPartial();
          } else {
            wireProtocol_ = value;
          }
          onChanged();
        } else {
          wireProtocolBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public Builder clearWireProtocol() {
        if (wireProtocolBuilder_ == null) {
          wireProtocol_ = null;
          onChanged();
        } else {
          wireProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getWireProtocolBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWireProtocolFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getWireProtocolOrBuilder() {
        if (wireProtocolBuilder_ != null) {
          return wireProtocolBuilder_.getMessageOrBuilder();
        } else {
          return wireProtocol_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : wireProtocol_;
        }
      }
      /**
       * <pre>
       * compiled specification of write protocol (serialized using "protoc -o")
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet wire_protocol = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getWireProtocolFieldBuilder() {
        if (wireProtocolBuilder_ == null) {
          wireProtocolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getWireProtocol(),
                  getParentForChildren(),
                  isClean());
          wireProtocol_ = null;
        }
        return wireProtocolBuilder_;
      }

      private java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> knownDevices_ =
        java.util.Collections.emptyList();
      private void ensureKnownDevicesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          knownDevices_ = new java.util.ArrayList<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor>(knownDevices_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder> knownDevicesBuilder_;

      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> getKnownDevicesList() {
        if (knownDevicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(knownDevices_);
        } else {
          return knownDevicesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public int getKnownDevicesCount() {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.size();
        } else {
          return knownDevicesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor getKnownDevices(int index) {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.get(index);
        } else {
          return knownDevicesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder setKnownDevices(
          int index, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.set(index, value);
          onChanged();
        } else {
          knownDevicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder setKnownDevices(
          int index, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.set(index, builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder addKnownDevices(com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.add(value);
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder addKnownDevices(
          int index, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor value) {
        if (knownDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownDevicesIsMutable();
          knownDevices_.add(index, value);
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder addKnownDevices(
          com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.add(builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder addKnownDevices(
          int index, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder builderForValue) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.add(index, builderForValue.build());
          onChanged();
        } else {
          knownDevicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder addAllKnownDevices(
          java.lang.Iterable<? extends com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor> values) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, knownDevices_);
          onChanged();
        } else {
          knownDevicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder clearKnownDevices() {
        if (knownDevicesBuilder_ == null) {
          knownDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          knownDevicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public Builder removeKnownDevices(int index) {
        if (knownDevicesBuilder_ == null) {
          ensureKnownDevicesIsMutable();
          knownDevices_.remove(index);
          onChanged();
        } else {
          knownDevicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder getKnownDevicesBuilder(
          int index) {
        return getKnownDevicesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder getKnownDevicesOrBuilder(
          int index) {
        if (knownDevicesBuilder_ == null) {
          return knownDevices_.get(index);  } else {
          return knownDevicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public java.util.List<? extends com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder> 
           getKnownDevicesOrBuilderList() {
        if (knownDevicesBuilder_ != null) {
          return knownDevicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(knownDevices_);
        }
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder addKnownDevicesBuilder() {
        return getKnownDevicesFieldBuilder().addBuilder(
            com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.getDefaultInstance());
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder addKnownDevicesBuilder(
          int index) {
        return getKnownDevicesFieldBuilder().addBuilder(
            index, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.getDefaultInstance());
      }
      /**
       * <pre>
       * descriptors of allowed devices
       * </pre>
       *
       * <code>repeated .DeviceDescriptor known_devices = 4;</code>
       */
      public java.util.List<com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder> 
           getKnownDevicesBuilderList() {
        return getKnownDevicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder> 
          getKnownDevicesFieldBuilder() {
        if (knownDevicesBuilder_ == null) {
          knownDevicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptor.Builder, com.satoshilabs.trezor.lib.protobuf.TrezorConfig.DeviceDescriptorOrBuilder>(
                  knownDevices_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          knownDevices_ = null;
        }
        return knownDevicesBuilder_;
      }

      private int validUntil_ ;
      /**
       * <pre>
       * expiration timestamp
       * </pre>
       *
       * <code>optional uint32 valid_until = 5;</code>
       */
      public boolean hasValidUntil() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * expiration timestamp
       * </pre>
       *
       * <code>optional uint32 valid_until = 5;</code>
       */
      public int getValidUntil() {
        return validUntil_;
      }
      /**
       * <pre>
       * expiration timestamp
       * </pre>
       *
       * <code>optional uint32 valid_until = 5;</code>
       */
      public Builder setValidUntil(int value) {
        bitField0_ |= 0x00000010;
        validUntil_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * expiration timestamp
       * </pre>
       *
       * <code>optional uint32 valid_until = 5;</code>
       */
      public Builder clearValidUntil() {
        bitField0_ = (bitField0_ & ~0x00000010);
        validUntil_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Configuration)
    }

    // @@protoc_insertion_point(class_scope:Configuration)
    private static final com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration();
    }

    public static com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Configuration>
        PARSER = new com.google.protobuf.AbstractParser<Configuration>() {
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configuration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Configuration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    public com.satoshilabs.trezor.lib.protobuf.TrezorConfig.Configuration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceDescriptor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceDescriptor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\032 google/protobuf/descript" +
      "or.proto\"^\n\020DeviceDescriptor\022\021\n\tvendor_i" +
      "d\030\001 \001(\r\022\022\n\nproduct_id\030\002 \001(\r\022\025\n\rserial_nu" +
      "mber\030\003 \001(\t\022\014\n\004path\030\004 \001(\t\"\271\001\n\rConfigurati" +
      "on\022\026\n\016whitelist_urls\030\001 \003(\t\022\026\n\016blacklist_" +
      "urls\030\002 \003(\t\0229\n\rwire_protocol\030\003 \002(\0132\".goog" +
      "le.protobuf.FileDescriptorSet\022(\n\rknown_d" +
      "evices\030\004 \003(\0132\021.DeviceDescriptor\022\023\n\013valid" +
      "_until\030\005 \001(\rB3\n#com.satoshilabs.trezor.l" +
      "ib.protobufB\014TrezorConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_DeviceDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeviceDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceDescriptor_descriptor,
        new java.lang.String[] { "VendorId", "ProductId", "SerialNumber", "Path", });
    internal_static_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Configuration_descriptor,
        new java.lang.String[] { "WhitelistUrls", "BlacklistUrls", "WireProtocol", "KnownDevices", "ValidUntil", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
