// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package com.satoshilabs.trezor.protobuf;

public final class TrezorStorage {
  private TrezorStorage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StorageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 version = 1;
    /**
     * <code>required uint32 version = 1;</code>
     *
     * <pre>
     * version of storage
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     *
     * <pre>
     * version of storage
     * </pre>
     */
    int getVersion();

    // optional .HDNodeType node = 2;
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    boolean hasNode();
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType getNode();
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder();

    // optional string mnemonic = 3;
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    boolean hasMnemonic();
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    java.lang.String getMnemonic();
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    com.google.protobuf.ByteString
        getMnemonicBytes();

    // optional bool passphrase_protection = 4;
    /**
     * <code>optional bool passphrase_protection = 4;</code>
     *
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     */
    boolean hasPassphraseProtection();
    /**
     * <code>optional bool passphrase_protection = 4;</code>
     *
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     */
    boolean getPassphraseProtection();

    // optional uint32 pin_failed_attempts = 5;
    /**
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     *
     * <pre>
     * number of failed PIN attempts
     * </pre>
     */
    boolean hasPinFailedAttempts();
    /**
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     *
     * <pre>
     * number of failed PIN attempts
     * </pre>
     */
    int getPinFailedAttempts();

    // optional string pin = 6;
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    boolean hasPin();
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    java.lang.String getPin();
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    com.google.protobuf.ByteString
        getPinBytes();

    // optional string language = 7;
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    boolean hasLanguage();
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    java.lang.String getLanguage();
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    // optional string label = 8;
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code Storage}
   *
   * <pre>
   **
   * Internal persistent storage of device
   * </pre>
   */
  public static final class Storage extends
      com.google.protobuf.GeneratedMessage
      implements StorageOrBuilder {
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Storage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Storage defaultInstance;
    public static Storage getDefaultInstance() {
      return defaultInstance;
    }

    public Storage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Storage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 18: {
              com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = node_.toBuilder();
              }
              node_ = input.readMessage(com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(node_);
                node_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mnemonic_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              passphraseProtection_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pinFailedAttempts_ = input.readUInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              pin_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              language_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              label_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satoshilabs.trezor.protobuf.TrezorStorage.internal_static_Storage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satoshilabs.trezor.protobuf.TrezorStorage.internal_static_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.class, com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.Builder.class);
    }

    public static com.google.protobuf.Parser<Storage> PARSER =
        new com.google.protobuf.AbstractParser<Storage>() {
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Storage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     *
     * <pre>
     * version of storage
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     *
     * <pre>
     * version of storage
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // optional .HDNodeType node = 2;
    public static final int NODE_FIELD_NUMBER = 2;
    private com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType node_;
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    public boolean hasNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    public com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType getNode() {
      return node_;
    }
    /**
     * <code>optional .HDNodeType node = 2;</code>
     *
     * <pre>
     * BIP-32 node (mnemonic cannot be used if this is present)
     * </pre>
     */
    public com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder() {
      return node_;
    }

    // optional string mnemonic = 3;
    public static final int MNEMONIC_FIELD_NUMBER = 3;
    private java.lang.Object mnemonic_;
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    public boolean hasMnemonic() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    public java.lang.String getMnemonic() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mnemonic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mnemonic = 3;</code>
     *
     * <pre>
     * BIP-39 mnemonic (node cannot be used if this is present)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMnemonicBytes() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnemonic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool passphrase_protection = 4;
    public static final int PASSPHRASE_PROTECTION_FIELD_NUMBER = 4;
    private boolean passphraseProtection_;
    /**
     * <code>optional bool passphrase_protection = 4;</code>
     *
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     */
    public boolean hasPassphraseProtection() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool passphrase_protection = 4;</code>
     *
     * <pre>
     * whether to require passphrase to decrypt node or stretch mnemonic
     * </pre>
     */
    public boolean getPassphraseProtection() {
      return passphraseProtection_;
    }

    // optional uint32 pin_failed_attempts = 5;
    public static final int PIN_FAILED_ATTEMPTS_FIELD_NUMBER = 5;
    private int pinFailedAttempts_;
    /**
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     *
     * <pre>
     * number of failed PIN attempts
     * </pre>
     */
    public boolean hasPinFailedAttempts() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 pin_failed_attempts = 5;</code>
     *
     * <pre>
     * number of failed PIN attempts
     * </pre>
     */
    public int getPinFailedAttempts() {
      return pinFailedAttempts_;
    }

    // optional string pin = 6;
    public static final int PIN_FIELD_NUMBER = 6;
    private java.lang.Object pin_;
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    public boolean hasPin() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    public java.lang.String getPin() {
      java.lang.Object ref = pin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pin = 6;</code>
     *
     * <pre>
     * current PIN
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPinBytes() {
      java.lang.Object ref = pin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string language = 7;
    public static final int LANGUAGE_FIELD_NUMBER = 7;
    private java.lang.Object language_;
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string language = 7;</code>
     *
     * <pre>
     * current language
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string label = 8;
    public static final int LABEL_FIELD_NUMBER = 8;
    private java.lang.Object label_;
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 8;</code>
     *
     * <pre>
     * device label
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      node_ = com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.getDefaultInstance();
      mnemonic_ = "";
      passphraseProtection_ = false;
      pinFailedAttempts_ = 0;
      pin_ = "";
      language_ = "";
      label_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasNode()) {
        if (!getNode().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, node_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMnemonicBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, passphraseProtection_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, pinFailedAttempts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPinBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getLanguageBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getLabelBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, node_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMnemonicBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, passphraseProtection_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, pinFailedAttempts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPinBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getLanguageBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getLabelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.satoshilabs.trezor.protobuf.TrezorStorage.Storage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Storage}
     *
     * <pre>
     **
     * Internal persistent storage of device
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.satoshilabs.trezor.protobuf.TrezorStorage.StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.satoshilabs.trezor.protobuf.TrezorStorage.internal_static_Storage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.satoshilabs.trezor.protobuf.TrezorStorage.internal_static_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.class, com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.Builder.class);
      }

      // Construct using com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nodeBuilder_ == null) {
          node_ = com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.getDefaultInstance();
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        mnemonic_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        passphraseProtection_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        pinFailedAttempts_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        pin_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        language_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.satoshilabs.trezor.protobuf.TrezorStorage.internal_static_Storage_descriptor;
      }

      public com.satoshilabs.trezor.protobuf.TrezorStorage.Storage getDefaultInstanceForType() {
        return com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.getDefaultInstance();
      }

      public com.satoshilabs.trezor.protobuf.TrezorStorage.Storage build() {
        com.satoshilabs.trezor.protobuf.TrezorStorage.Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.satoshilabs.trezor.protobuf.TrezorStorage.Storage buildPartial() {
        com.satoshilabs.trezor.protobuf.TrezorStorage.Storage result = new com.satoshilabs.trezor.protobuf.TrezorStorage.Storage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (nodeBuilder_ == null) {
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mnemonic_ = mnemonic_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.passphraseProtection_ = passphraseProtection_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pinFailedAttempts_ = pinFailedAttempts_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pin_ = pin_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.label_ = label_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.satoshilabs.trezor.protobuf.TrezorStorage.Storage) {
          return mergeFrom((com.satoshilabs.trezor.protobuf.TrezorStorage.Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.satoshilabs.trezor.protobuf.TrezorStorage.Storage other) {
        if (other == com.satoshilabs.trezor.protobuf.TrezorStorage.Storage.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasMnemonic()) {
          bitField0_ |= 0x00000004;
          mnemonic_ = other.mnemonic_;
          onChanged();
        }
        if (other.hasPassphraseProtection()) {
          setPassphraseProtection(other.getPassphraseProtection());
        }
        if (other.hasPinFailedAttempts()) {
          setPinFailedAttempts(other.getPinFailedAttempts());
        }
        if (other.hasPin()) {
          bitField0_ |= 0x00000020;
          pin_ = other.pin_;
          onChanged();
        }
        if (other.hasLanguage()) {
          bitField0_ |= 0x00000040;
          language_ = other.language_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000080;
          label_ = other.label_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (hasNode()) {
          if (!getNode().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.satoshilabs.trezor.protobuf.TrezorStorage.Storage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.satoshilabs.trezor.protobuf.TrezorStorage.Storage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 version = 1;
      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       *
       * <pre>
       * version of storage
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       *
       * <pre>
       * version of storage
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       *
       * <pre>
       * version of storage
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       *
       * <pre>
       * version of storage
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // optional .HDNodeType node = 2;
      private com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType node_ = com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder> nodeBuilder_;
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public boolean hasNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType getNode() {
        if (nodeBuilder_ == null) {
          return node_;
        } else {
          return nodeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public Builder setNode(com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          nodeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public Builder setNode(
          com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          nodeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public Builder mergeNode(com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType value) {
        if (nodeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              node_ != com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.getDefaultInstance()) {
            node_ =
              com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.newBuilder(node_).mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          nodeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.getDefaultInstance();
          onChanged();
        } else {
          nodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder getNodeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNodeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      public com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder getNodeOrBuilder() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilder();
        } else {
          return node_;
        }
      }
      /**
       * <code>optional .HDNodeType node = 2;</code>
       *
       * <pre>
       * BIP-32 node (mnemonic cannot be used if this is present)
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeType.Builder, com.satoshilabs.trezor.protobuf.TrezorType.HDNodeTypeOrBuilder>(
                  node_,
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }

      // optional string mnemonic = 3;
      private java.lang.Object mnemonic_ = "";
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public boolean hasMnemonic() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public java.lang.String getMnemonic() {
        java.lang.Object ref = mnemonic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mnemonic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMnemonicBytes() {
        java.lang.Object ref = mnemonic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnemonic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public Builder setMnemonic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mnemonic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public Builder clearMnemonic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mnemonic_ = getDefaultInstance().getMnemonic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnemonic = 3;</code>
       *
       * <pre>
       * BIP-39 mnemonic (node cannot be used if this is present)
       * </pre>
       */
      public Builder setMnemonicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mnemonic_ = value;
        onChanged();
        return this;
      }

      // optional bool passphrase_protection = 4;
      private boolean passphraseProtection_ ;
      /**
       * <code>optional bool passphrase_protection = 4;</code>
       *
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       */
      public boolean hasPassphraseProtection() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool passphrase_protection = 4;</code>
       *
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       */
      public boolean getPassphraseProtection() {
        return passphraseProtection_;
      }
      /**
       * <code>optional bool passphrase_protection = 4;</code>
       *
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       */
      public Builder setPassphraseProtection(boolean value) {
        bitField0_ |= 0x00000008;
        passphraseProtection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool passphrase_protection = 4;</code>
       *
       * <pre>
       * whether to require passphrase to decrypt node or stretch mnemonic
       * </pre>
       */
      public Builder clearPassphraseProtection() {
        bitField0_ = (bitField0_ & ~0x00000008);
        passphraseProtection_ = false;
        onChanged();
        return this;
      }

      // optional uint32 pin_failed_attempts = 5;
      private int pinFailedAttempts_ ;
      /**
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       *
       * <pre>
       * number of failed PIN attempts
       * </pre>
       */
      public boolean hasPinFailedAttempts() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       *
       * <pre>
       * number of failed PIN attempts
       * </pre>
       */
      public int getPinFailedAttempts() {
        return pinFailedAttempts_;
      }
      /**
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       *
       * <pre>
       * number of failed PIN attempts
       * </pre>
       */
      public Builder setPinFailedAttempts(int value) {
        bitField0_ |= 0x00000010;
        pinFailedAttempts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 pin_failed_attempts = 5;</code>
       *
       * <pre>
       * number of failed PIN attempts
       * </pre>
       */
      public Builder clearPinFailedAttempts() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pinFailedAttempts_ = 0;
        onChanged();
        return this;
      }

      // optional string pin = 6;
      private java.lang.Object pin_ = "";
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public boolean hasPin() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public java.lang.String getPin() {
        java.lang.Object ref = pin_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPinBytes() {
        java.lang.Object ref = pin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public Builder setPin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public Builder clearPin() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pin_ = getDefaultInstance().getPin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pin = 6;</code>
       *
       * <pre>
       * current PIN
       * </pre>
       */
      public Builder setPinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pin_ = value;
        onChanged();
        return this;
      }

      // optional string language = 7;
      private java.lang.Object language_ = "";
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000040);
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string language = 7;</code>
       *
       * <pre>
       * current language
       * </pre>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        language_ = value;
        onChanged();
        return this;
      }

      // optional string label = 8;
      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000080);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 8;</code>
       *
       * <pre>
       * device label
       * </pre>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        label_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Storage)
    }

    static {
      defaultInstance = new Storage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Storage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstorage.proto\032\013types.proto\"\261\001\n\007Storage" +
      "\022\017\n\007version\030\001 \002(\r\022\031\n\004node\030\002 \001(\0132\013.HDNode" +
      "Type\022\020\n\010mnemonic\030\003 \001(\t\022\035\n\025passphrase_pro" +
      "tection\030\004 \001(\010\022\033\n\023pin_failed_attempts\030\005 \001" +
      "(\r\022\013\n\003pin\030\006 \001(\t\022\020\n\010language\030\007 \001(\t\022\r\n\005lab" +
      "el\030\010 \001(\tB0\n\037com.satoshilabs.trezor.proto" +
      "bufB\rTrezorStorage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Storage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Storage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Storage_descriptor,
              new java.lang.String[] { "Version", "Node", "Mnemonic", "PassphraseProtection", "PinFailedAttempts", "Pin", "Language", "Label", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.satoshilabs.trezor.protobuf.TrezorType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
